---
title: "ESM 244 Lab Week 2"
author: "Roupen Khanjian"
date: "1/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# For PCA:
library(ggfortify)

# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures
library(patchwork)

```

### Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>%  # helper function for select
  drop_na() %>% # drop na obs from any column
  scale() %>% 
  prcomp()
  
penguin_pca$rotation # loadings are here for the PCs  

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

autoplot(penguin_pca,
         data = penguin_complete,
         colour = "species",
         loadings = TRUE,
         loadings.label = TRUE) +
  theme_minimal() #  can add ggplot functions to autoplot, can also change arrow size and other things. 

# other ways to make pca biplots in r as well. 
```

### Part 2: ggplot2 customization & reading in different file types

#### read in a .xlsx file & do some wrangling

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% # default is to convert all col names to snake case
  mutate(across(where(is.character), tolower)) %>%  # for any char col use func `to_lower`
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>%  #  Here we are removing the last 4 characters from the col. 
  filter(confidentiality == "public")

# usually someone has already written a function you want to use. 
```

Make a customized graph

```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds)) +
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()

fish_plot

ggplotly(fish_plot) 

### Use gghighlight to highlight certain series

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line() +
  theme_minimal() +
  gghighlight(nmfs_name == "tunas")

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8) # highlight only nmfs_name where max pounds is > 1e8
```

#### Read in from a URL, `lubridate()`. `mutate()`, make a graph with months in logical order


```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv") %>% 
  clean_names()
```

```{r}
monroe_ts <- monroe_wt %>% 
  mutate(date = mdy(date)) %>% # convert date column to a date data type
  mutate(record_month = month(date)) %>%   # extract the month
  mutate(month_name = month.abb[record_month]) %>%  # add a new column with month abbreviation 
  mutate(month_name = fct_reorder(month_name, record_month)) # convert char to factor and set order based on another col

ggplot(data = monroe_ts, aes(x = month_name, y = total_k_wh)) +
  geom_jitter() # will show alphabetically if we dont convert month_name to factor and set order to match number of the month. 

ggplot(data = monroe_ts, aes(x = month_name, y = total_k_wh)) +
  geom_jitter() # works after we added that last line in monroe_ts
```

### Part 3: Compund figures with `patchwork`

```{r}
graph_a <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

graph_b <- ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species), show.legend = FALSE)

# Use | to put graphs side by side
# Use / to put graphs one over the other

graph_c <-  (graph_a | graph_b) / fish_plot & theme_dark() # adds the theme to all 3 plots

graph_c

# to export can use ggsave(here("fig", "graph_c_rk.png")) will look for last graph run

ggsave(here("fig", "graph_c_rk.png"), width = 5, height = 6) # worked!
```


